version: '3'
services:
  airflow:
    image: apache/airflow:2.9.1
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__FERNET_KEY=something-random-here
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__FERNET_KEY=bvw-m0ciayZivs4QMx96HED3SqpwLSGwc3_Ph1zd5Ow=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    command: bash -c "airflow db init && airflow users create --username admin --firstname Freddy --lastname Dev --role Admin --email admin@example.com --password admin && airflow webserver & airflow scheduler"
    ports:
      - "8080:8080"

